server:
  port: $PORT
database:
  host: $DATABASE_HOST
  port: $DATABASE_PORT
  username: $DATABASE_USER
  password: $DATABASE_PASSWORD
  name: $DATABASE_NAME
queue:
  enabled: true
  url: $QUEUE_URL
